name: â“ Question
description: Ask a HUB-SDK question
# title: " "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a HUB-SDK â“ Question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the Ultralytics [Docs](https://docs.ultralytics.com), [issues](https://github.com/ultralytics/hub-sdk/issues) and [discussions](https://github.com/ultralytics/hub-sdk/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the HUB-SDK [issues](https://github.com/ultralytics/hub-sdk/issues) and [discussions](https://github.com/ultralytics/hub-sdk/discussions) and found no similar questions.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
