# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# HUB-SDK documentation CI

name: HUB-SDK Docs

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - uses: ultralytics/actions/setup-uv@main
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          uv pip install -e ".[dev]"
        shell: bash
      - name: Build Docs and Check for Warnings
        run: |
          mkdocs build --strict
        shell: bash
