# Ultralytics HUB-SDK 🚀, AGPL-3.0 license
# HUB-SDK Continuous Testing (CT) GitHub Actions

name: Continuous Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ubuntu-latest

    env:
      FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
      ULTRALYTICS_HUB_API: ${{ vars.ULTRALYTICS_HUB_API }}
      ULTRALYTICS_HUB_WEB: ${{ vars.ULTRALYTICS_HUB_WEB }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd tests
        pip install -r requirements.txt

    - name: Download Test Data
      run: |
        cd tests
        python utils/test_data.py download

    - name: Run pytest
      run: python -m pytest -v -m "smoke" tests